import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Grid from '@material-ui/core/Grid';

import { ProfileView } from '../../../src/components';

const Profile: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Profile view</title>
        <meta name="A profile" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container>
        <ProfileView />
      </Grid>
    </div>
  );
};

export default Profile;
