import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Grid from '@material-ui/core/Grid';

import { ProfileView } from '../../../src/components';

const Profile: NextPage = () => {
  return (
    <Grid container>
      <Head>
        <title>Profile view</title>
        <meta name="A profile" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container>
        <ProfileView
          id={'p1'}
          name={'profile 1'}
          city={'South Africs, Kwa-Zulu Natal, Durban city'}
          imgUrl={
            'https://images.unsplash.com/photo-1628935746762-14b90583073f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80'
          }
        />
      </Grid>
    </Grid>
  );
};

export default Profile;
